spring.application.name=medisphere-backend

server.port=8080

# MongoDB Atlas
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=medisphere

# Kafka
spring.kafka.bootstrap-servers=localhost:9092