spring.application.name=medisphere-backend

server.port=8080

# MongoDB Atlas / Local fallback
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/medisphere}
spring.mongodb.database=medisphere

# Kafka
spring.kafka.bootstrap-servers=localhost:9092